### ISSUE TITLE
Unreliable bulk action to Un-assign all Open/etc tickets on set to unavailable

### ISSUE THREAD

**Issue by jeremiahcurrier** [zendesklabs/out_of_office_app#193]
Intermittently when unassigning many on marking as unavailable some of the tickets will not actually become unassigned. 

Option 1. ReWrite 'unassign many' f(x) to be asynchronous - won't totally fix the problem. 

Feature Request VS **Bug**; Bug latter as the user will expect the action to complete 100% of the time.

Note: If the growl notification doesn't go off, the unassign job didn't finish.

**Comment by dpawluk** [comment]
Using update many to bulk un-assign  may mitigate the issue my spooling up a job rather than you running your own?

**Comment by Nebopolis** [comment]
@dpawluk - this is for adding/removing ticket tags - there is no bulk update endpoints for that, just /tickets/{ID}/tags.json

**Comment by Nebopolis** [comment]
turns out, there actually is a bulk endpoint for this - who'd have known? Solved!
