### ISSUE TITLE
Two enhancements to add more graceful error handling 

### ISSUE THREAD

**Issue by jeremiahcurrier** [zendesklabs/out_of_office_app#200]
1. 422 agent and/or admin marking owner as OOO - fail f(x) does not fire notification
 * problem: not popping error at all
 * solution: ensure the .fail() is called - avoids forever request #foreverAloneRequest
2. 429 as well
 * when this happens specifically - ensure graceful fail notification to user with message about no more than 15 updates in 10 minutes etc etc

**Notes:**

*throw in a few options for 422 / 429 in app.js fail f(x)*

```
    postPage: function(request, data, index, done, fail) { 
        util.appFramework.ajax(request, data[index]).done(function() {
            index++;
            if(index == data.length) { //if we are at the last index
                done();
            } else {
                util.postPage(request, data, index, done, fail);                
            }
        }).fail(function(error) {
            util.appFramework.trigger('network_error', {request: request, requestType: 'postPage', index: index, data: data, error: error});
            fail(error);  //error here
        });
    },
```

**Comment by Nebopolis** [comment]
Finished
