### ISSUE TITLE
Increase duration of some notifications (See issue details)

### ISSUE THREAD

**Issue by jeremiahcurrier** [zendesklabs/out_of_office_app#201]
* persist all services notification longer
* Add notification that the action could take a moment please wait
* Add consistent error handling if request hangs/fails to increase trust in the app
* improve app responsiveness w/ async requests for tags.json

We may want to break this issue into separate issues? CC @Nebopolis

**Comment by Nebopolis** [comment]
https://zendesk.atlassian.net/browse/TIERTHREE-212

**Comment by Nebopolis** [comment]
null and void now that notifications are less needed
