### ISSUE TITLE
updating in Nav bar is not working

### ISSUE THREAD

**Issue by safaa-alnablsi** [zendesklabs/out_of_office_app#206]
Hello,
I pulled the repo and after `zat package`, it's not working and also it's different style from the old app.

**Comment by Nebopolis** [comment]
Thanks for your interest - there is work ongoing to get a new version with updated styles working. For the current functional version you can use https://github.com/zendesklabs/out_of_office_app/releases/tag/v2.5.4 or install the app from the zendesk apps marketplace. 

If you are interested in contributing I'll apologize for things not working now, the events for the navbar portion of the app no longer line up with the rest of the app which is what causes the error. I'll be taking some time this week to get things cleaned up in that regard.

**Comment by Nebopolis** [comment]
Hi @safaa-alnablsi thank you for your patience with this. The current master is now in a much better state, so please feel free to look at it whenever. There are a number of improvements to how the app functions and I have tested all of the sections as working.
