### ISSUE TITLE
tag agent_ooo does not work

### ISSUE THREAD

**Issue by adekauff1** [zendesklabs/out_of_office_app#222]
Hello,

I think the tag "agent_ooo" is not working properly. It seems that the app Out of Office automatically sets up this tag once an agent sets itself as unavailable but how can I know that the tag is well set?
I am trying to set up the following : when an agent is OOO, if one of his solved/pending/on-hold ticket gets an answer from end user, it will reopen as "open" and i want these tickets to be assign to a specific group. However, so far it does not seem to work, and I think it's because the tag "agent_ooo" is not applying.

**Comment by Nebopolis** [comment]
Hi @adekauff1,

You should be able to see the addition of the tag in the ticket event history:
<img width="184" alt="screen shot 2017-02-16 at 1 28 31 pm" src="https://cloud.githubusercontent.com/assets/59228/23037425/e5b077a6-f44b-11e6-92a9-0ba77564ede5.png">
<img width="374" alt="screen shot 2017-02-16 at 1 34 04 pm" src="https://cloud.githubusercontent.com/assets/59228/23037605/9e074e92-f44c-11e6-9a2c-a2fd729e99f0.png">

The primary function of the app is to add and remove the `agent_ooo` tag, so if that isn't happening you may want to try uninstalling and reinstalling the app. You should be able to modify the default trigger to have the behavior you are looking for. 

-Ben
