### ISSUE TITLE
App not removing OOO tag

### ISSUE THREAD

**Issue by randallmom26** [zendesklabs/out_of_office_app#223]
We have a user that is experiencing problems with her Out Of Office App. She was out of the office recently and marked that in her OOO App. When she returned she marked herself as Available. However,  all of her tickets are still being re-assigned to her main group. It is not recognizing that she is back in the office, therefore it is not removing the tag on her tickets showing her as Out-Of-Office. I ahve tried to set her to Available and Unavailable to fix it with no improvement. 
 
I checked both of the Triggers and they appear to not have been modified since the initial install back in August. However, after reading them I am not sure which one would recognize that she is back in the office IF the ticket was never opened while she was out of the office. Here is how they are set up:
 
Tag: out-of-office app unassign trigger [System Trigger]
Meet all of the following conditions:
Ticket: Tags - Contains at least one of the following = agent_ooo
Ticket: Assignee = Changed
Perform these actions:
Ticket: Remove tags = agent_ooo
 
Ticket: out-of-office app unassign trigger [System Trigger]
Meet all of the following conditions:
Ticket: Tags - Contains at least one of the following = agent_ooo
Ticket: Status - Is = Open
Ticket: Assignee = Not Changed
Perform these actions:
Ticket: Assignee = {blank}
Ticket: Remove tags = agent_ooo
 
Zendesk has advised that this is an error in the app. I have also installed and re-installed the app itself with no improvement.

**Comment by Nebopolis** [comment]
The next release adds some additional tools to debug this issue
