### ISSUE TITLE
Icon for OOO does not have alpha transparency

### ISSUE THREAD

**Issue by luckman212** [zendesklabs/out_of_office_app#225]
Was happy to discover the OutOfOffice lab (https://www.zendesk.com/apps/out-of-office/) but a bit sad that the icon on the left navbar sticks out like a sore thumb (screenshot below).  Can this be fixed?

![badicon](https://user-images.githubusercontent.com/1992842/27094704-019dc93e-5039-11e7-8211-736b75166f1a.png)

**Comment by Nebopolis** [comment]
@luckman212 Thanks for the report - I'm currently working on some updates, so I'll get that fixed as well.

**Comment by luckman212** [comment]
4 months ... can we get that icon fixed?

**Comment by Nebopolis** [comment]
Hi @luckman212 - Sorry for the wait. I've been trying to track down a bug in the app ticket updating code, which has taken up the time i have allocated for the app. I think I finally have a solution in sight so I will be revisiting all the other updates that would be going out in an update. Thank you for your interest in the app, and I can promise it won't take another 4 months.

**Comment by Nebopolis** [comment]
Fixed in the next release
