### ISSUE TITLE
Out of office trigger is randomly on even though Zendesk user is available 

### ISSUE THREAD

**Issue by angelika-aron** [zendesklabs/out_of_office_app#229]
On several occasions one of our Zendesk users was available but the out of office trigger re-assigned the ticket into the unassigned queue.

**Comment by Nebopolis** [comment]
@angelika-aron Thanks for the report, sorry for the slow response here. Are you able to reproduce this consistently? Or is it an intermittent issue.

**Comment by Nebopolis** [comment]
The next release adds some additional tools to debug this issue
