### ISSUE TITLE
Important reporting related problem - Possibility to set to which agent Ticket updates via the app are attributed

### ISSUE THREAD

**Issue by hheusala** [zendesklabs/out_of_office_app#230]
When Agent puts him/herself OoO via the app this ticket update is done in Zendesk metrics by the Agent himself.

Lots of users use "assignee updated" in their very important agent effort related metrics in Insights/Gooddata. For a large consumer customer service there are easily hundreds of tickets that are not closed (even solved ones get this update) where one agent is an assignee. When this agent puts himself OoO or back from OoO via this app this results in all of those hundreds of tickets getting a touch/update by the assignee. Which then messed totally up all reports using Assignee updated as their timeframe.

Solution for this would be to have a setting under app settings for inputting the agent to whom all of these updates made by this app would be attributed. This way reports wouldn't get messed up

**Comment by Nebopolis** [comment]
@hheusala unfortunately this is not possible within the app framework. The updates being made are happening using the browser session of the agent who clicks the button, and changing the attribution would require a server-side component which makes the requests on behalf of the app.
